export const dammyData = [
  {
    uid: "12938179afdoifhja",
    username: "tom",
    email: "tom@email.com",
    password: "123456",
    companies: {
        id:"11010",
        name: "株式会社freee",
        industy: "IT・情報通信",
        sector: "エンジニア",
        myPage: {
          url: "https://mui.com/material-ui/react-stepper/",
          id: "aiueo",
          password: "12345",
        },
        steps: [
          {
            id: "aa9",
            text: "エントリー",
            completed: true,
            current: false,
            selected: false,
            region: "東京",
            startDate: "2024-12-01",
            endDate: "2024-12-03",
            startTime: "12:00",
            endTime: "18:00",
            limitDate: "2024-11-07",
            limitTime:"23:59"
          },
          {
            id: "a12",
            text: "説明会",
            completed: true,
            current: false,
            selected: false,
            region: "東京",
            startDate: "2024-12-01",
            endDate: "2024-12-03",
            startTime: "12:00",
            endTime: "18:00",
            limitDate: "2024-11-07",
            limitTime:"23:59"
          },
          {
            id: "a65",
            text: "面接",
            completed: false,
            current: true,
            selected: false,
            region: "東京",
            startDate: "2024-12-01",
            endDate: "2024-12-03",
            startTime: "12:00",
            endTime: "18:00",
            limitDate: "2024-11-07",
            limitTime:"23:59"
          },
          {
            id: "af9",
            text: "適正検査",
            completed: false,
            current: false,
            selected: false,
            region: "東京",
            startDate: "2024-12-01",
            endDate: "2024-12-03",
            startTime: "12:00",
            endTime: "18:00",
            limitDate: "2024-11-07",
            limitTime:"23:59"
          },
          {
            id: "a42",
            text: "インターン長期",
            completed: false,
            current: false,
            selected: false,
            region: "東京",
            startDate: "2024-12-01",
            endDate: "2024-12-03",
            startTime: "12:00",
            endTime: "18:00",
            limitDate: "2024-11-07",
            limitTime:"23:59"
          },
          {
            id: "a09",
            text: "本選考",
            completed: false,
            current: false,
            selected: false,
            region: "東京",
            startDate: "2024-12-01",
            endDate: "2024-12-03",
            startTime: "12:00",
            endTime: "18:00",
            limitDate: "2024-11-07",
            limitTime:"23:59"
          },
        ],
      }
    
  },
];
